apps/account/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('', views.top, name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

apps/work_report/urls.py
# -*- coding: utf-8 -*-

from django.urls import path, re_path
from . import views



app_name = 'work_report'

urlpatterns = [
    path('work_report/', views.show_work_report, name='work_report'),
    path('time_stamp/', views.show_time_stamp, name='time_stamp'),
    path('settings/', views.show_settings, name='settings'),

    path('export_excel/', views.export_excel, name='export_excel'),
    path('reset_report/', views.reset_report, name='reset_report'),

    re_path(r'^.*/*exec/$', views.exec_ajax, name='exec'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.account.urls')),
    # path('work_report/', include('apps.work_report.urls')),
    path('', include('apps.work_report.urls')),
]

apps/account/models.py
# -*- coding: utf-8 -*-

import uuid

from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
                                        UserManager)
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserRole(models.Model):
    role_id = models.CharField(_('role id'),
                max_length=10, blank=True, null=True)
    role_name = models.CharField(_('role'),
                max_length=10, blank=True, null=True)
    
    def __str__(self):
        return self.role_name


class coustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(_('employee id'),
                primary_key=True, default=uuid.uuid4, editable=False)
    no = models.IntegerField(_('employee number'),
                blank=True, null=True, unique=True)
    username = models.CharField(_('user name'), max_length=20, default='guestuser')
    username_kana = models.CharField(_('user name kana'), max_length=20, default='guestuser')
    department = models.CharField(_('user department'), max_length=20, default='guestuser')
    roles = models.ForeignKey(UserRole,
                on_delete=models.SET_NULL, blank=True, null=True)
    joined_date = models.DateField(_('Join date'),
                blank=True, null=True)
    tel = models.CharField(_('phone number'), max_length=15,
                blank=True, null=True)
    email = models.EmailField(_('email address'), unique=True)
    photo = models.ImageField(upload_to='accounts/',
                blank=True, null=True)
    detail = models.TextField(_('user detail'),
                max_length=500, blank=True, null=True)
    created_date = models.DateField(_('created date'),
                blank=True, null=True, default=timezone.now)
    update_date = models.DateField(_('update date'),
                blank=True, null=True)
    status = models.BooleanField(default=True)

    is_staff = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=True)
    
    #EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = coustomUserManager()

    @property
    def is_staff_property(self):
        return self.is_admin

    @property
    def is_superuser_property(self):
        return self.is_admin

    def __str__(self):
        return f"{self.no}_{self.username}"

apps/account/forms.py
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる

apps/account/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render

from .forms import LoginForm


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'register/login.html'


class Logout(LogoutView):
    """ログアウトページ"""
    template_name = 'register/top.html' 

def top(request):
    # return render(request, 'register/top.html', {'user': request.user})
    return render(request, 'time_stamp/time_stamp.html', {'user': request.user})

apps/account/templates/register/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- jQuery読み込み -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- BootstrapのJS読み込み -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/base_style.css' %}">

    <title>勤怠管理</title>
</head>
<body>
    <!-- ナビバー -->
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'register:top' %}">勤怠管理</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto list-inline">
                <li class="list-inline-item{% if request.path == '/time_stamp/' or request.path == '/' %} active{% endif %}"">
                    <a class="nav-item nav-link" href="{% url 'work_report:time_stamp' %}">打刻</a>
                </li>
                <li class="list-inline-item{% if request.path == '/work_report/' %} active{% endif %}"">
                    <a class="nav-item nav-link" href="{% url 'work_report:work_report' %}">作業報告書</a>
                </li>
                <li class="list-inline-item{% if request.path == '/settings/' %} active{% endif %}">
                    <a class="nav-item nav-link" href="{% url 'work_report:settings' %}">設定</a>
                </li>
            </ul>

            <ul class="navbar-nav list-inline">
                <li class="list-inline-item">
                    <a class="nav-item nav-link" href="{% url 'register:logout' %}">ログアウト</a>
                </li>
            </ul>

            {% else %}
            <ul class="navbar-nav mr-auto list-inline">
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'register:login' %}">
                        ようこそ、ゲスト！ログインはこちら
                    </a>
                </li>
            </ul>

            {% endif %}

        </div>
    </nav>

    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" -->
    <!-- integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" -->
    <!-- crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" -->
    <!-- integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" -->
    <!-- crossorigin="anonymous"></script> -->
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" -->
    <!-- integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" -->
    <!-- crossorigin="anonymous"></script> -->
</body>
</html>

apps/account/templates/register/login.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{% url 'register:top' %}" />
                {% csrf_token %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

apps/account/templates/register/top.html
{% extends "register/base.html" %}
{% block content %}

{% if user.is_authenticated %}
    <h4>ログインユーザ：{{ user.username }}様<h4>

    {% block main %}
    {% endblock %}

{% endif %}

{% endblock %}