apps/work_report/urls.py
# -*- coding: utf-8 -*-

from django.urls import path, re_path
from . import views



app_name = 'work_report'

urlpatterns = [
    path('work_report/', views.show_work_report, name='work_report'),
    path('time_stamp/', views.show_time_stamp, name='time_stamp'),
    path('settings/', views.show_settings, name='settings'),

    path('export_excel/', views.export_excel, name='export_excel'),
    path('reset_report/', views.reset_report, name='reset_report'),

    re_path(r'^.*/*exec/$', views.exec_ajax, name='exec'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.account.urls')),
    # path('work_report/', include('apps.work_report.urls')),
    path('', include('apps.work_report.urls')),
]

apps/work_report/forms.py
from django import forms

from .models import WorkDetail

class TimeStampForm(forms.ModelForm):

    class Meta:
        model = WorkDetail
        fields = ('start_time', 'end_time',)

apps/work_report/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
import calendar
from datetime import datetime, timedelta, time

from .forms import TimeStampForm

from .models import WorkReport, WorkDetail, Status, ReportSettings

from apps.account.models import User

import openpyxl
from openpyxl import utils
from openpyxl.styles import Protection
import email.utils

import collections

from . import time_util


def show_time_stamp(request):
    return render(request, 'time_stamp/time_stamp.html')

def show_work_report(request):
    """
        勤務報告書のリンクを押したときの処理
    """

    # リクエストクエリから年と月を取得します
    year = request.GET.get("year")
    month = request.GET.get("month")

    # リクエストクエリがない場合は当日
    if not year:
        year = datetime.now().year
    else:
        year = int(year)

    if not month:
        month = datetime.now().month
    else:
        month = int(month)

    user_id = request.user.no # ログインしたユーザの社員番号

    report_period = datetime(year=year, month=month, day=1) # 対象月の初日

    # 対象月の報告書
    # work_report = WorkReport.objects.get_or_create(
    work_report = get_work_report(user_id=user_id, report_period=report_period)

    # 当月の報告書明細
    work_details = get_work_detail(report_no=work_report.report_no,report_period=report_period,user_id=user_id)

    month_range = calendar.monthrange(year,month)[1]
    first_date = datetime.strptime(str(year)+str(month).zfill(2),"%Y%m")
    month_date = [first_date + timedelta(days=i) for i in range(month_range)]

    ret_dict = {
        'month_date' : month_date,
        "work_report" : work_report,
        "work_details" : work_details.values()
    }

    return render(request, 'work_report/work_report.html', ret_dict)

def show_settings(request):
    user_id = request.user.no # ログインしたユーザの社員番号

    #ユーザIDからReportSettingsを検索してレコードが存在しない場合は作成
    report_settings = ReportSettings.objects.get_or_create(
        user_id = User.objects.get(no=user_id)
    )[0]

    return render(request, 'settings/settings.html', {'report_settings': report_settings})


def exec_ajax(request):

    user_id = request.user.no

    if request.method == "GET":
        data = dict(request.GET.items())

        if data["type"] == "change_year_month":
            year = int(data["year"])
            month = int(data["month"])

            ret_dict = {
                "year":year,
                "month":month,
            }

            return change_report(request,ret_dict)


    elif request.method == "POST":
        data = dict(request.POST.items())

        # 打刻画面
        if data["type"] == "time_stamp":
            report_period = get_first_date()

            # 当月の報告書
            # work_report = WorkReport.objects.get_or_create(
            work_report = get_work_report(user_id=user_id, report_period=report_period)

            # 当月分の報告書明細
            work_details = get_work_detail(report_no=work_report.report_no,report_period=report_period,user_id=user_id)
            # 当日の報告書明細
            work_detail = work_details[datetime.today().date()]

            stamp_time = data["time"].replace(" ","")

            # 出勤
            if data["method"] == "entry-work":
                work_detail.start_time = stamp_time
                if not work_detail.break1 and not work_detail.break2: # どっちにも入っていない場合デフォルト値を設定する。
                    work_detail.break1 = 1
                work_detail.save()

            # 退勤
            elif data["method"] == "leave-work":
                work_detail.end_time = stamp_time
                work_detail.save()

            # 休憩入
            elif data["method"] == "entry-break":
                work_detail.start_break = stamp_time
                work_detail.save()

            # 休憩戻
            elif data["method"] == "leave-break":
                work_detail.end_break = stamp_time
                work_detail.save()

            return HttpResponse()

        # 作業報告書
        elif data["type"] == "change_work_report":
            # 入力値に誤りがなければresponseを返す

            try:
                target = data["target"]
                year = int(data["year"])
                month = int(data["month"])

                report_period = datetime(year=year, month=month, day=1) # 対象月の初日

                # 対象月の報告書
                # work_report = WorkReport.objects.get_or_create(
                work_report = get_work_report(user_id=user_id, report_period=report_period)

                if target == "project_name":
                    project_name = data["project_name"]
                    work_report.project_name = project_name
                    work_report.save()

                elif target == "site_work_time":
                    site_work_time = time_util.convert_to_clock_time(data["site_work_time"])

                    if not site_work_time:
                        raise Exception

                    work_report.site_work_time = site_work_time
                    work_report.save()

                elif target == "report_detail":
                    date=int(data["date"])
                    start_time=time_util.convert_to_clock_time(data["start_time"])
                    end_time=time_util.convert_to_clock_time(data["end_time"])
                    break1_time=time_util.convert_to_float_time(time_util.convert_to_clock_time(data["break1_time"]))
                    break2_time=time_util.convert_to_float_time(time_util.convert_to_clock_time(data["break2_time"]))
                    status_code=int(data["status_code"])
                    remarks=data["remarks"]

                    # 対象月分の報告書明細
                    work_details = get_work_detail(report_no=work_report.report_no,report_period=report_period,user_id=user_id)

                    # 対象日
                    target_date = report_period.replace(day=date)
                    # 対象日の報告書明細
                    work_detail = work_details[target_date]

                    work_detail.start_time = start_time
                    work_detail.end_time = end_time
                    work_detail.break1 = break1_time
                    work_detail.break2 = break2_time
                    work_detail.status = Status.objects.get(code=status_code)
                    work_detail.remarks = remarks
                    work_detail.save()

                elif target is None:
                    raise Exception

                return HttpResponse(status=200)

            except Exception as e:
                return HttpResponse(status=500) # なんか不備がある場合の戻り値

        # 設定値
        elif data["type"] == "change_report_settings":
            try:
                report_settings = ReportSettings.objects.get_or_create(
                    user_id = User.objects.get(no=user_id)
                )[0]

                start_time=time_util.convert_to_clock_time(data["start_time"])
                end_time=time_util.convert_to_clock_time(data["end_time"])
                break1_time=time_util.convert_to_clock_time(data["break1_time"])
                break2_time=time_util.convert_to_clock_time(data["break2_time"])
                holidays = data["holidays"]
                project_name = data["project_name"]

                report_settings.start_time = start_time
                report_settings.end_time = end_time
                report_settings.break1 = break1_time
                report_settings.break2 = break2_time
                report_settings.holidays = holidays
                report_settings.project_name = project_name
                report_settings.save()

                return HttpResponse(status=200)

            except Exception as e:
                return HttpResponse(status=500)


def get_work_report(report_period,user_id):
    """
        report_periodの一か月分で検索したwork_reportを返す。
        レコードが存在しない場合、作成してデフォルト値を適用して返す
    """
    try:
        work_report = WorkReport.objects.get(
            user_id = User.objects.get(no=user_id),
            report_period = report_period
        )

    except Exception as e: # レコードが存在しない場合
        # 設定値を取得
        report_settings = ReportSettings.objects.get_or_create(
            user_id = User.objects.get(no=user_id)
        )[0]

        work_report = WorkReport.objects.create(
            user_id = User.objects.get(no=user_id),
            report_period = report_period
        )
        work_report.project_name = report_settings.project_name
        work_report.save()

    return work_report


def get_work_detail(report_no,report_period,user_id):
    """
        report_no,report_periodの一か月分で検索したwork_detailと日付のディクショナリを返す。
        レコードが存在しない場合、作成してデフォルト値を適用して返す
    """
    report_year = report_period.year
    report_month = report_period.month

    month_length = calendar.monthrange(report_period.year,report_period.month)[1]
    month_dates = [report_period.replace(day=day+1) for day in range(month_length)]


    try:
        work_details = {work_date:WorkDetail.objects.get(
            report_no=WorkReport.objects.get(report_no=report_no),
            work_date=work_date
        ) for work_date in month_dates}

    except Exception as e: # レコードが存在しない場合
        # 設定値を取得
        report_settings = ReportSettings.objects.get_or_create(
            user_id = User.objects.get(no=user_id)
        )[0]
        holiday_week = report_settings.holiday_week

        # レコード作成
        work_details = {work_date:WorkDetail.objects.create(
            report_no=WorkReport.objects.get(report_no=report_no),
            work_date=work_date
        ) for work_date in month_dates}

        # 設定値を適用
        for work_date,work_detail in work_details.items():
            if not work_date.strftime("%a") in holiday_week:

apps/work_report/templates/work_report/work_report.html
{% extends "register/top.html" %}
{% load static %}

{% block main %}

<html id="work-report">
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/colors.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/wickedpicker.min.css' %}">
        <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
        <title>test</title>
    </head>
    <body>
        <div class="header">
            <table>
                <tr class="year-month">
                    <td class="editable">
                        <input id="year" type="number" max="9999" min="1000" value='{{ work_report.report_period.year }}'>
                    </td>
                    <th>年</th>
                    <td class="editable">
                        <input id="month" type="number" max="12" min="1" value='{{ work_report.report_period.month }}'>
                    </td>
                    <th>月</th>
                </tr>
                <tr class="project-name">
                    <th colspan="4">プロジェクト名</td>
                    <td class="editable"><input class="project-name" type="text" value="{{ work_report.project_name }}"></td>
                </tr>
            </table>
            <table>
                <tr>
                    <th>出勤日数</th>
                    <td class="work-days">{{ work_report.work_days }}</td>
                </tr>
                <tr>
                    <th>休日日数</th>
                    <td class="holidays">{{ work_report.holidays }}</td>
                </tr>
            </table>
            <div class="btn btn-primary btn-lg" data-toggle="modal" data-target="#reset"><a href="{% url 'work_report:reset_report' %}?year={{work_report.report_period.year}}&month={{ work_report.report_period.month }}">初期化</a></div>
            <div class="btn btn-success btn-lg" data-toggle="modal" data-target="#output_excel"><a href="{% url 'work_report:export_excel' %}?year={{work_report.report_period.year}}&month={{ work_report.report_period.month }}">Excel出力</a></div>
        </div>
        <div class="record-table">
            <table>
                <thead>
                    <tr>
                        <th colspan="2">項目</th>
                        <th colspan="2">作業時間</th>
                        <th colspan="2">休憩</th>
                        <th rowspan="3">合計</th>
                        <th rowspan="3">作業時間</th>
                        <th rowspan="3">残業時間</th>
                        <th rowspan="3">深夜作業</th>
                        <th rowspan="3">休日出勤</th>
                        <th rowspan="3">ステータス</th>
                        <th rowspan="3">備考</th>
                    </tr>
                    <tr>
                        <th rowspan="2">日</th>
                        <th rowspan="2">曜日</th>
                        <th>始業</th>
                        <th>終業</th>
                        <th>5:00</th>
                        <th>22:00</th>
                    </tr>
                    <tr>
                        <th>時分</th>
                        <th>時分</th>
                        <th>22:00</th>
                        <th>29:00</th>
                    </tr>
                </thead>
                <tbody>
                    {% for report_detail in work_details %}
                    <tr id="{{ work_report.report_period.year }}-{{ work_report.report_period.month }}-{{ report_detail.work_date.day }}" class="report-detail{% if report_detail.day_status is not Null %} {{ report_detail.day_status }}{% endif %}">
                        <td><div class="date">{{ report_detail.work_date|date:"j" }}</div></td>
                        <td><div class="week">{{ report_detail.work_date|date:"D" }}</div></td>
                        <td class="editable"><input type="text" name="" class="time start-time" {% if not report_detail.start_time is None %}value="{{ report_detail.start_time }}"{% endif %}/></td>
                        <td class="editable"><input type="text" name="" class="time end-time" {% if not report_detail.end_time is None %}value="{{ report_detail.end_time }}"{% endif %}/></td>
                        <td class="editable"><input type="text" name="" class="time break1-time" value="{{ report_detail.break1_time }}" /></td>
                        <td class="editable"><input type="text" name="" class="time break2-time" value="{{ report_detail.break2_time }}" /></td>
                        <td><input type="text" name="" class="time" readonly="true" value="{{ report_detail.total_time }}" /></td>
                        <td><input type="text" name="" class="time" readonly="true" value="{{ report_detail.mean_time }}" /></td>
                        <td><input type="text" name="" class="time" readonly="true" value="{{ report_detail.over_time }}" /></td>
                        <td><input type="text" name="" class="time" readonly="true" value="{{ report_detail.midnight_over_time }}" /></td>
                        <td><input type="text" name="" class="time" readonly="true" value="{{ report_detail.holiday_work }}" /></td>
                        <td class="editable">
                            <select class="status" name="status">
                                <option value="none" {% if report_detail.status.code == 0 %}selected{% endif %}></option>
                                <option value="paid" {% if report_detail.status.code == 1 %}selected{% endif %}>有給</option>
                                <option value="sp-holiday" {% if report_detail.status.code == 2 %}selected{% endif %}>特別休業</option>
                                <option value="substitution" {% if report_detail.status.code == 3 %}selected{% endif %}>代休</option>
                                <option value="absenteeism" {% if report_detail.status.code == 4 %}selected{% endif %}>欠勤</option>
                                <option value="late" {% if report_detail.status.code == 5 %}selected{% endif %}>遅刻</option>
                                <option value="leave-early" {% if report_detail.status.code == 6 %}selected{% endif %}>早退</option>
                                <option value="all-night" {% if report_detail.status.code == 7 %}selected{% endif %}>徹夜</option>
                                <option value="shift-work" {% if report_detail.status.code == 8 %}selected{% endif %}>シフト出勤</option>
                                <option value="shift-break" {% if report_detail.status.code == 9 %}selected{% endif %}>シフト休</option>
                                <option value="holiday" {% if report_detail.status.code == 10 %}selected{% endif %}>祝日</option>
                                <option value="holiday-work" {% if report_detail.status.code == 11 %}selected{% endif %}>休日出勤</option>
                                <option value="sp-leave" {% if report_detail.status.code == 12 %}selected{% endif %}>慶弔休暇</option>
                                <option value="paid-absent" {% if report_detail.status.code == 13 %}selected{% endif %}>有給/欠勤</option>
                                <option value="other" {% if report_detail.status.code == 14 %}selected{% endif %}>その他</option>
                            </select>
                        </td>
                        <td class="editable"><input type="text" class="remarks" value="{{report_detail.remarks}}"></td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="6">社内作業含み合計</th>
                        <td>{{ work_report.report_total_time }}</td>
                        <td>{{ work_report.report_mean_time }}</td>
                        <td>{{ work_report.report_over_time }}</td>
                        <td>{{ work_report.report_midnight_over_time }}</td>
                        <td>{{ work_report.report_holiday_work }}</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr class="site-work-time">
                        <th colspan="6">現場作業の合計時間</th>
                        <td colspan="2" class="editable"><input type="text" class="total-time" value="{{ work_report.site_work_time }}"/></td>
                        <th colspan="3">合計差分</th>
                        <td>{{ work_report.diff_total_time }}</td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="footer"></div>

        <!-- Modal -->
        <div class="modal fade" id="output_excel" tabindex="-1" role="dialog" aria-labelledby="outputExcelModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-body">
                Excelをダウンロードします。<br>しばらくお待ちください。
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade" id="reset" tabindex="-1" role="dialog" aria-labelledby="resetModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-body">
                データをクリアして初期値を適用します。
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
              </div>
            </div>
          </div>
        </div>

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
    <script src="{% static 'js/work_report.js' %}"></script>

    </body>

</html>

{% endblock %}